image: 
    file: .gitpod.Dockerfile
tasks:
  - command: wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.1.149/quarto-1.1.149-linux-amd64.deb 
  - command: sudo gdebi *.deb -y
  - command: rm *.deb
 
